CREATE TABLE Autor (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(150) NOT NULL, 
    Nacionalidade VARCHAR(50),
    Removido BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE Leitor (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(150) NOT NULL, 
    Email VARCHAR(100) UNIQUE,
    Removido BOOLEAN NOT NULL DEFAULT FALSE 
);

CREATE TABLE Livro (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Titulo VARCHAR(255) NOT NULL,
    AutorID INT NOT NULL, 
    DataPublicacao DATE NOT NULL, 
    EdicaoCusto DECIMAL(6, 2) NOT NULL, 
    Removido BOOLEAN NOT NULL DEFAULT FALSE, 
    FOREIGN KEY (AutorID) REFERENCES Autor(ID)
);

CREATE TABLE Emprestimo (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    LeitorID INT NOT NULL,
    LivroID INT NOT NULL, 
    DataEmprestimo DATE NOT NULL,
    DataDevolucaoPrevista DATE, 
    Status VARCHAR(50) NOT NULL,
    Removido BOOLEAN NOT NULL DEFAULT FALSE, 
    FOREIGN KEY (LeitorID) REFERENCES Leitor(ID),
    FOREIGN KEY (LivroID) REFERENCES Livro(ID)
);